
#ifndef RGBLED_CONFIG_H
#define RGBLED_CONFIG_H

#define NUMBER_OF_PROGRESS_RINGS 2

#define TOTAL_LEDS_OUTER_RING 24
#define TOTAL_LEDS_INNER_RING 16
#define TOTAL_LEDS (TOTAL_LEDS_OUTER_RING + TOTAL_LEDS_INNER_RING)

#define RGB_LED_TOTAL_LEDS TOTAL_LEDS

#endif  // RGBLED_CONFIG_H
