
#ifndef RGBLED_CONFIG_H
#define RGBLED_CONFIG_H

#define NUMBER_OF_PROGRESS_RINGS 2

#define NOF_LEDS_OUTER_RING 60
#define START_INDEX_OUTER_RING 0
#define END_INDEX_OUTER_RING (NOF_LEDS_OUTER_RING - 1)

#define NOF_LEDS_MIDDLE_RING 32
#define START_INDEX_MIDDLE_RING (NOF_LEDS_OUTER_RING + START_INDEX_OUTER_RING)
#define END_INDEX_MIDDLE_RING (NOF_LEDS_MIDDLE_RING + START_INDEX_MIDDLE_RING - 1)

#define NOF_LEDS_INNER_RING 12
#define START_INDEX_INNER_RING (NOF_LEDS_MIDDLE_RING + START_INDEX_MIDDLE_RING)
#define END_INDEX_INNER_RING (NOF_LEDS_INNER_RING + START_INDEX_INNER_RING - 1)

#define NOF_LEDS_BTN_RING 4
#define START_INDEX_BTN_RING (NOF_LEDS_INNER_RING + START_INDEX_INNER_RING)
#define END_INDEX_BTN_RING (NOF_LEDS_BTN_RING + START_INDEX_BTN_RING - 1)

#define TOTAL_LEDS (NOF_LEDS_OUTER_RING + NOF_LEDS_MIDDLE_RING + NOF_LEDS_INNER_RING + NOF_LEDS_BTN_RING)

#define RGB_LED_TOTAL_LEDS TOTAL_LEDS

#endif // RGBLED_CONFIG_H
