#ifndef POMODORO_FSM_INTERFACE_H
#define POMODORO_FSM_INTERFACE_H

#include "Common.h"

typedef enum
{
    E_PFSM_STATE_IDLE = 0U,
    E_PFSM_STATE_WORKTIME,
    E_PFSM_STATE_BREAKTIME,
    E_PFSM_STATE_SEEKING_ATTENTION,
} PomodoroFsm_state_e;

#endif // POMODORO_FSM_INTERFACE_H