#ifndef POMODOROCONTROL_DATATYPES_H
#define POMODOROCONTROL_DATATYPES_H

#include "Common.h"

#define MINUTES_IN_HOUR 60
#define TOTAL_MINUTES (MINUTES_IN_HOUR * 2)

/**
 * FSM Config
 */
typedef enum
{
    STATE_IDLE = 0,
    STATE_WORKTIME_INIT,
    STATE_WORKTIME,
    STATE_WARNING,
    STATE_BREAKTIME_INIT,
    STATE_BREAKTIME,
    STATE_CANCEL_SEQUENCE_INIT,
    STATE_CANCEL_SEQUENCE_RUNNING,
    STATE_CANCEL_SEQUENCE_HALTED,
    STATE_LAST,
} PCTRL_State_t;

typedef enum
{
    EVENT_POMODORO_SEQUENCE_START = 0,
    EVENT_TRIGGER_BTN_LONG_PRESS,
    EVENT_TRIGGER_BTN_RELEASED,
    EVENT_SEQUENCE_COMPLETE,
    EVENT_SEQUENCE_PENDING,
    EVENT_LAST
} PCTRL_Event_e;

/**
 * PomodoroConfig
 */
typedef enum
{
    E_CFG_INVALID = 0,
    E_CFG_WORKTIME,
    E_CFG_BREAKTIME,
    E_CFG_OFF,
    E_CFG_LAST
} PCTRL_Config_e;

#endif // POMODOROCONTROL_DATATYPES_H
