#ifndef POMODOROCONTROL_DATATYPES_H
#define POMODOROCONTROL_DATATYPES_H

typedef enum {
  POMDOORO_CONTROL_STATE__IDLE,
  POMODORO_CONTROL_STATE__STARTING_SEQUENCE,
  POMODORO_CONTROL_STATE__WORKTIME,
  POMODORO_CONTROL_STATE__WARNING,
  POMODORO_CONTROL_STATE__BREAKTIME,
  POMODORO_CONTROL_STATE__CANCEL_SEQUENCE,
  POMODORO_CONTROL_STATE__INVALID
} PomodoroControl_State_t;

typedef enum {
  POMODORO_CONTROL_STATE_FN_STATE__PENDING,
  POMODORO_CONTROL_STATE_FN_STATE__SUCCESS,
  POMODORO_CONTROL_STATE_FN_STATE__ERROR
} PomodoroControl_StateFn_status_t;

typedef struct {
  BOOL bStartPomodoroEventReceived;
  BOOL bTriggerButtonIsPressedContinuously;
} PomodoroControl_internalStatus_t;

#endif  // POMODOROCONTROL_DATATYPES_H
