
#ifndef STANDBYCONTROL_DATATYPES_H
#define STANDBYCONTROL_DATATYPES_H

typedef enum {
  E_STANDBY_STATE_IDLE = 0U,
  E_STANDBY_STATE_SEEKING_ATTENTION = 1U,
  E_STANDBY_STATE_POMODORO = 2U
} StandbyControl_state_t;

#define STATE_EXECUTION_COMPLETE TRUE
#define STATE_EXECUTION_INCOMPLETE FALSE

typedef enum {
  E_STANDBY_STATUS_SEQUENCE_COMPLETE = 0U,
  E_STANDBY_STATUS_SEQUENCE_INCOMPLETE = 1U
} StandbyControl_SequenceStatus_e;

#endif  // STANDBYCONTROL_DATATYPES_H
